[versions]
agp = "9.4.0"
androidx-localbroadcast = "1.1.0"
appcompat = "1.8.0"
dokka = "2.2.0"
jtorctl = "0.4.5.7"
nmcp = "1.6.2"
tor-android = "0.4.9.11"
version-catalog-update = "1.1.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-localbroadcast = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcast" }
jtorctl = { module = "info.guardianproject:jtorctl", version.ref = "jtorctl" }
tor-android = { module = "info.guardianproject:tor-android", version.ref = "tor-android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
