name: Tor Android AAR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build AAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew :tor-android-binary:assembleRelease

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: tor-android-binary-aar
          path: tor-android-binary/build/outputs/aar/*.aar
